
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/projectdefaults"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
