
name: Build and Push Docker Images

on:
  push:
    branches:
      - master
      - staging

jobs:
  build-and-push-matrix:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16, 18, 20, 22, 24, 'lts']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push with matrix
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 5140/docker-egg:node-${{ matrix.node_version }}
          build-args: NODE_VERSION=${{ matrix.node_version }}

  build-and-push-snapshot:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push snapshot
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 5140/docker-egg:snapshot
          build-args: NODE_VERSION=lts
